# Generated by Django 5.0.2 on 2024-03-07 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.IntegerField(blank=True, null=True)),
                ('item_price', models.FloatField(blank=True, null=True)),
                ('branch_id', models.IntegerField(blank=True, null=True)),
                ('instruction', models.CharField(blank=True, max_length=256, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('discount', models.FloatField(blank=True, null=True)),
                ('total_price', models.FloatField(blank=True, null=True)),
                ('item_variation_total', models.IntegerField(blank=True, null=True)),
                ('item_extra_total', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_id', models.IntegerField(blank=True, null=True)),
                ('subtotal', models.FloatField(blank=True, null=True)),
                ('token', models.TextField(blank=True, null=True)),
                ('discount', models.FloatField(blank=True, null=True)),
                ('delivery_charge', models.FloatField(blank=True, null=True)),
                ('delivery_time', models.FloatField(blank=True, null=True)),
                ('total', models.CharField(blank=True, max_length=256, null=True)),
                ('order_type', models.IntegerField(blank=True, null=True)),
                ('is_advance_order', models.IntegerField(blank=True, null=True)),
                ('source', models.IntegerField(blank=True, null=True)),
                ('address_id', models.IntegerField(blank=True, null=True)),
                ('coupon_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
