# Generated by Django 5.0.2 on 2024-03-12 05:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(blank=True, null=True)),
                ('branch_id', models.IntegerField(blank=True, null=True)),
                ('instruction', models.CharField(blank=True, max_length=256, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('discount', models.IntegerField(blank=True, null=True)),
                ('total_price', models.FloatField(blank=True, null=True)),
                ('item_variation_total', models.IntegerField(blank=True, null=True)),
                ('item_extra_total', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_id', models.CharField(blank=True, max_length=256, null=True)),
                ('subtotal', models.FloatField(blank=True, null=True)),
                ('token', models.TextField(blank=True, null=True)),
                ('discount', models.FloatField(blank=True, null=True)),
                ('delivery_charge', models.IntegerField(blank=True, null=True)),
                ('delivery_time', models.FloatField(blank=True, null=True)),
                ('total', models.FloatField(blank=True, default=0, null=True)),
                ('order_type', models.IntegerField(blank=True, null=True)),
                ('is_advance_order', models.BooleanField(default=False, null=True)),
                ('source', models.IntegerField(blank=True, null=True)),
                ('address_id', models.IntegerField(blank=True, null=True)),
                ('coupon_id', models.IntegerField(blank=True, null=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('items', models.ManyToManyField(to='shopping_cart.item')),
            ],
        ),
    ]
